### PR TITLE
Added retry iteration to RetryForeverAsync

### PR DESCRIPTION
**Pull request by kmcginnes**
It would be nice to know what iteration of retry you are on. This allows for logging every 5th iteration, or publishing a message on the first failure.

### CODE REVIEW

**Comment by michael-wolfenden** [comment]
Thanks @kmcginnes for you contribution, I will look at merging in the next couple of days

**Comment by kmcginnes** [comment]
Awesome. There's probably room for a little more consistency between the sync and non-async APIs.

**Comment by joelhulen** [comment]
@kmcginnes I've noticed that this PR has conflicts that need to be resolved. Could you please resolve the conflicts?

**Comment by reisenberger** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
