### PR TITLE
Run in parallel all tests which do not manipulate the abstracted clock

### PR DESCRIPTION
**Pull request by jbergens**
Done during hackaton

### CODE REVIEW

**Comment by reisenberger** [comment]
:+1: LGTM!  Takes another minute off the build time, in our local tests.  Yay!

**Comment by reisenberger** [comment]
Awesome @jbergens .  Thanks for this!  Closes #359

**Comment by reisenberger** [comment]
@jbergens  Would you be able to retarget this PR against the `v560dev` branch if you have a moment?  (Should be possible to change on the existing PR.) Thanks!

**Comment by jbergens** [comment]
Will try.

Johan

Den 17 nov. 2017 17:38 skrev "reisenberger" <notifications@github.com>:

**Comment by jbergens** [comment]
Changed the target branch to v560dev as requested.

**Pull request merged**
