### PR TITLE
Removed useless using statements. Now using expression-bodied members…

### PR DESCRIPTION
**Pull request by moerwald**
* Polly.Shared/Registry
* Polly.SharedSpecs/Registry

557, https://github.com/App-vNext/Polly/issues/557

### Details on the issue fix or feature implementation

* Removed useless using statements. 
* Now using expression-bodied members and inline-out variables

### Confirm the following

- [ ]  I have merged the latest changes from the dev vX.Y branch
- [x]  I have successfully run a local build
- [ ]  I have included unit tests for the issue/feature
- [ ]  I have targeted the PR against the latest dev vX.Y branch

### CODE REVIEW

**Comment by reisenberger** [comment]
Thanks @moerwald !  Please could you rebase the PR on the [latest v7.0.0 dev branch](https://github.com/App-vNext/Polly/tree/v700) ?  

You will find also that @seanfarrow and I made some changes to PolicyRegistry as part of [this merge earlier in the v700 branch](https://github.com/App-vNext/Polly/commit/9a2fcfd5b2a75d69f903804d42e792553eb23732), not sure if you will find anything else worth tidying among that.

Thanks again for contributing!

**Comment by moerwald** [comment]
@reisenberger rebased against v700 as described here: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request. Hope I've done it the right way.

**Comment by SeanFarrow** [comment]
I’ll review this later/tomorrow.
Did you add a readonly registry property to the IReadonlyRegistry tests, or was it already there?

**Comment by moerwald** [comment]
@SeanFarrow 
>>> Did you add a readonly registry property to the IReadonlyRegistry tests, or was it already there?

I added it.

**Comment by moerwald** [comment]
@reisenberger thanks for the guidance. I've changed the PR base branch to v700.

**Comment by SeanFarrow** [comment]
@, moerwald
On first look this looks good, however could you remove the readOnly registry property and just reference the private variable, it is readonly and only created in the constructor, so the property is redundant and not needed.

**Comment by moerwald** [comment]
@SeanFarrow done.

**Comment by reisenberger** [comment]
@moerwald Apologies, I am going back on my previous comment: Can I suggest that we abandon this PR?  It looks good in GitHub web gui (and might squash ok), but the history seen from git command line and desktop git apps is of diverged branches. Can I ask you to branch afresh from the head of the v7.0.0 branch, and then re-impose your changes from [commit 443c5b9](https://github.com/App-vNext/Polly/pull/564/commits/443c5b9e50287f2d8c8dae951cb4cdfdd4a9ff7c)?  Thanks for your patience!

Second reason: @SeanFarrow @moerwald , I think some confusion may have crept in around the `ReadOnlyRegistry` property in the `IReadOnlyPolicyRegistrySpecs`.  This dates from a couple of years ago when the tests were originally authored; @moerwald had only added a `readonly` modifier (which seems reasonable) to the private `_registry` field. I'd like to suggest we retain the `ReadOnlyRegistry` property and don't re-impose [the second commit](https://github.com/App-vNext/Polly/pull/564/commits/0f7e5b3731c3a3fc8b670cad762d314589031c9c) on the new PR.  

To explain; It's a bit of a nit, but the intent of `IReadOnlyPolicyRegistrySpecs` is to test PolicyRegistry as seen through the `IReadOnlyPolicyRegistry<T>` interface, so I think that is what the tests should test.  There's a subtle difference between testing via `IReadOnlyPolicyRegistry<T>`, via `IPolicyRegistry<T>` or via the concrete class `PolicyRegistry<T>`, because the behaviour could be different if PolicyRegistry used explicit interface implementation, as [this gist shows](https://gist.github.com/reisenberger/d7cd8706c279bab4d8beb8efb1fa12a0).  A bit of a nit, as we don't actually use explicit implementation in PolicyRegistry, but retaining the `ReadOnlyRegistry` property means the tests do test what they say they test. ... ... Anyway, this distracts from the great work we are all doing tidying the codebase :+1: :+1: (_thank you!_), just wanted to explain why the tests had that approach.

Thanks for everything you are doing!

**Comment by SeanFarrow** [comment]
@ Reisenberger,

Whilst that all makes sense (and I agree with you), it might be worth adding some comments to the tests themselves to ensure this kind of thing doesn’t happen again?
I’m happy to do this once @moerwald<https://github.com/moerwald> has rebased and changed the commits.

**Comment by moerwald** [comment]
@reisenberger , no problem I'll close this PR (based on v700), and create a new one only containing the changes in Registry folder. I'll keep the unit tests untouched.

**Comment by reisenberger** [comment]
Hi @SeanFarrow . Re;

>Whilst that all makes sense (and I agree with you), it might be worth adding some comments to the tests themselves to ensure this kind of thing doesn’t happen again?
>I’m happy to do this once @moerwald<https://github.com/moerwald> has rebased and changed the commits.

... that's a great idea!  Please feel free to make a PR to add a note like that to `ReadOnlyPolicyRegistry` on `IReadOnlyPolicyRegistrySpecs` . I've merged @moerwald 's new PR already so that (after the many changes) we can get a merge on that 🙂 , but just add a comment in separate PR any time.

**Pull request closed without merging**
