### PR TITLE
V571on break delegate

### PR DESCRIPTION
**Pull request by erickhouse**
- Add a new delegate type that provides the previous transition state when the policy transitions to open
- new unit tests were provided for the advanced, basic / async, non-async circuit 
- All unit tests were run for all versions of the software

### CODE REVIEW

**Comment by reisenberger** [comment]
Thanks @erickhouse ! I should get to review this on Friday or Sunday afternoon.

This will (when merged) close #325.

**Comment by reisenberger** [comment]
Awesome, @erickhouse ! That's a perfect PR! :ok_hand:  :100:  

Could you [retarget the base branch of the PR](https://github.com/blog/2224-change-the-base-branch-of-a-pull-request) onto [`App-vNext::v571onBreakDelegate`](https://github.com/App-vNext/Polly/tree/v571onBreakDelegate)?  Then I'll merge.  We're moving toward a process where we don't merge to `master` until everything for that release is ready. (I'll merge `App-vNext::v571onBreakDelegate` to master later.)

(If you fancy digging further into Polly :grin:, #338 is a very similar pattern (add new input parameter to a policy event delegate), but no starting branch or pointers to similar tests on that one ...)

**Comment by erickhouse** [comment]
Great, Thanks! I just re-targeted to v571 instead of master. I'll take a look at 338.

**Comment by reisenberger** [comment]
Perfect.  Merging to v571 dev branch!  

fyi, I'll merge with "squash and merge": this means you'll see your three commits merged into one, in the base branch.  Sometimes, project owners will squash-while-merging (or ask you as a contributor to squash commits before merging).  If later commits are just minor tidies (as in this case), representing it all as one commit in the base branch is neater.  If individual commits represent substantive and different work, owners might tend to not squash while merging - keeps the original commits separate.

**Pull request merged**
