### PR TITLE
[Docs] Add sequence diagrams to timeout strategy

### PR DESCRIPTION
**Pull request by peter-csala**
# Pull Request

## The issue or feature being addressed

- When I was working on the Polly-Samples migration I've added several mermaid diagrams (for example: [1](https://github.com/App-vNext/Polly-Samples/blob/main/PollyTestWebApi/README.md#polly-test-web-api), [2](https://github.com/App-vNext/Polly-Samples/blob/main/PollyDemos/README.md#structure) to visualize the relationships).
- I thought it might make sense to further enhance the Polly documentation by adding sequence diagrams to it

## Details on the issue fix or feature implementation
- Added a happy path and unhappy path sequence diagram to the timeout strategy

### Preview
- [Live](https://github.com/peter-csala/Polly/blob/add-sequence-diagrams-to-timeout-strategy/docs/strategies/timeout.md#diagrams)

## Confirm the following

- [x]  I started this PR by branching from the head of the default branch
- [x]  I have targeted the PR to merge into the default branch
- [ ]  I have included unit tests for the issue/feature
- [x]  I have successfully run a local build

### CODE REVIEW

**Comment by martintmk** [comment]
Two notes:

- Please check whether this is supported by DocFx since that one is used for our docs: https://www.pollydocs.org/strategies/timeout.html
- I would move these under the `Defaults` section under `Diagram` or `Diagram flow` since these diagrams are for more advanced readers and w don't want to obscure the usage samples.

**Comment by martincostello** [comment]
> I'm not sure whether the pollydocs.org will do the same dynamic rendering as github.

Yeah, that was my first thought too.

**Comment by peter-csala** [comment]
>     * Please check whether this is supported by DocFx since that one is used for our docs: https://www.pollydocs.org/strategies/timeout.html

I've found these comments: 
- https://github.com/dotnet/docfx/issues/2292#issuecomment-522194766
- https://github.com/dotnet/docfx/issues/2292#issuecomment-562193524

and this plugin: https://github.com/dpvreony/docfx-mermaidjs

>     * I would move these under the `Defaults` section under `Diagram` or `Diagram flow` since these diagrams are for more advanced readers and w don't want to obscure the usage samples.

- Done

**Comment by martintmk** [comment]
> > ```
> > * Please check whether this is supported by DocFx since that one is used for our docs: https://www.pollydocs.org/strategies/timeout.html
> > ```
> 
> I've found these comments:
> 
> * [Addin for diagrams support dotnet/docfx#2292 (comment)](https://github.com/dotnet/docfx/issues/2292#issuecomment-522194766)
> * [Addin for diagrams support dotnet/docfx#2292 (comment)](https://github.com/dotnet/docfx/issues/2292#issuecomment-562193524)
> 
> and this plugin: https://github.com/dpvreony/docfx-mermaidjs
> 
> > ```
> > * I would move these under the `Defaults` section under `Diagram` or `Diagram flow` since these diagrams are for more advanced readers and w don't want to obscure the usage samples.
> > ```
> 
> * Done

Maybe just include these as images under `docs/media` ?

**Comment by martincostello** [comment]
> Maybe just include these as images under docs/media ?

That's probably the least friction way. We can still leave the diagrams in as HTML comments to make regenerating them easy.

**Comment by peter-csala** [comment]
> Maybe just include these as images under `docs/media` ?

On pollydocs you can switch back and forth between light and dark theme. 

If we could add mermaid support then the diagrams would align with the selected theme as well.

Screenshot 2023-10-16 at 14 54 29

If we stick with the image then which theme do we prefer?

**Comment by martincostello** [comment]
I would go with "normal" black on white if we don't go with a plugin.

**Review by martincostello — APPROVED** [review]

**Review by martintmk — APPROVED** [review]

**Comment by martincostello** [comment]
My guess would be the paths are slightly different when the docfx website is built.

I suggest running it locally and seeing what path it outputs and then tweaking the file to have the right path for pollydocs even if it breaks GitHub.

**Pull request merged**
