### PR TITLE
Expose Simmy APIs

### PR DESCRIPTION
**Pull request by vany0114**
# Pull Request

## The issue or feature being addressed
Exposes Simmy's API's so that we can start getting the release and docs ready. 

## Details on the issue fix or feature implementation
It just makes public the pipelines, etc.

## Confirm the following

- [x]  I started this PR by branching from the head of the default branch
- [x]  I have targeted the PR to merge into the default branch
- [ ]  I have included unit tests for the issue/feature
- [x]  I have successfully run a local build

### CODE REVIEW

**Comment by martincostello** [comment]
I suggest that we leave merging this and any other public-facing Simmy-related changes until Wednesday so we can get out the .NET 8.0 changes on Tuesday once .NET 8.0 ships as Polly 8.2, then Simmy can follow as 8.3.

**Comment by vany0114** [comment]
@martincostello @martintmk can we merge this guy?

**Comment by martintmk** [comment]
> @martincostello @martintmk can we merge this guy?

Yup, 8.2.0 is already out.

**Review by martincostello — APPROVED** [review]

**Review by martintmk — APPROVED** [review]

**Comment by martincostello** [comment]
What are the tasks left for releasing the Simmy changes? I imagine at a minimum we need to update the documentation?

**Comment by vany0114** [comment]
> What are the tasks left for releasing the Simmy changes? I imagine at a minimum we need to update the documentation?

Yep, that will be my next PR

**Pull request merged**
