### PR TITLE
PR and issue automation

### LINKED ISSUE #1167: Pull request automation?
To aid in the maintenance of Polly (dependabot updates, .NET SDK updates), it would be good to harness GitHub Actions and the GitHub API to perform some tasks automatically to reduce some of the human element.

The initial automation I'd like to add are:

- [Approve dependabot updates](https://github.com/martincostello/dotnet-patch-automation-sample/blob/main/.github/workflows/dependabot-approve.yml) (based on an allow-list) - example pull request https://github.com/justeattakeaway/httpclient-interception/pull/551
- [Updating the .NET SDK](https://github.com/martincostello/dotnet-patch-automation-sample/blob/main/.github/workflows/update-dotnet-sdk.yml) - example pull request https://github.com/martincostello/dotnet-patch-automation-sample/pull/107
- [Auto-approve .NET SDK updates](https://github.com/martincostello/dotnet-patch-automation-sample/blob/main/.github/workflows/approve-and-merge.yml) - example pull request https://github.com/martincostello/dotnet-patch-automation-sample/pull/107
- [Marking old issues and pull requests as stale](https://github.com/actions/stale#readme)

To get the most out of this, the first three ideas for automation needs to run as a GitHub user or app (bot), rather than use `GITHUB_TOKEN`, which has limitations in terms of triggering actions ([docs](https://docs.github.com/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow)) - otherwise CI runs aren't queued-up.

Assuming others are happy with these ideas, we'd just need a bot (or two; one to edit, one to approve) created in App-vNext (`pollybot`, `polly-reviewer`? ideas for better names welcome) and a private key to exchange for an access token to act on the bot's behalf added to the GitHub Actions secrets in this repo.

### PR DESCRIPTION
**Pull request by martincostello**
- Add the [dependency review action](https://github.com/actions/dependency-review-action#readme).
- Use the new `polly-updater-bot` app to apply the .NET SDK updates. This removes the need to close and re-open PRs raised by the workflow to get the CI to run.
- Add a workflow to approve and auto-merge dependabot updates for a trusted set of dependencies.
- Add a workflow to approve and auto-merge .NET SDK updates by the polly-updater-bot app.
- Automatically mark issues and pull requests as stale if there is no activity for 60 days.
- Automatically close stale issues and pull requests after 14 days.

Resolves #1167.

### CODE REVIEW

**Review by martintmk — APPROVED** [review]
lgtm, but I am no expert in GitHub workflows so take this review with a grain of salt.

**Review by joelhulen — APPROVED** [review]
This looks good to me.

**Comment by martincostello** [comment]
Cool - thanks both. I'll merge this as-is, and we can tweak anything in a future PR.

**Comment by martincostello** [comment]
And so does the reviewer 🥳

https://github.com/App-vNext/Polly/pull/1376#pullrequestreview-1507414638

**Comment by joelhulen** [comment]
Awesome!

**Pull request merged**
