### PR TITLE
Use NuSpec refgen to put correct dotnet targets

### PR DESCRIPTION
**Pull request by onovotny**
Addresses #59

### CODE REVIEW

**Comment by onovotny** [comment]
Not sure about the cake build stuff, but this works...

**Comment by joelhulen** [comment]
This is perfect. Thanks!

**Comment by michael-wolfenden** [comment]
@onovotny I'm a bit confused. I thought I was updating the nuspec file as part of the build script using the ReferenceGenerator cli. For clarification was this incorrect?. 

In this pull request it looks like you've manually specified the dependendies in the nuspec file, but my understanding was that this is the whole point of ReferenceGenerator ie to automatically generate these so if you add a new dependency to your project, it will correctly be added to the nuspec.

Any clarification would be much appreciated.

**Comment by onovotny** [comment]
So there's two issues, both bugs I think. The main issue is that the tool wasn't picking up the dependencies correctly. If you noticed, the dotnet section was blank, when in fact it shouldn't have been.

In theory, you should be able to run the tool without having it as a reference (though I'm always baffled by why people would want that as you're less shielded from cmd line arguments changes that are handled by having a matching targets file).

1. The tool looks for the presence of a `packages.config` or a `project.json` and got confused. As the scenarios I'd previously tested relied on one of those files being there, I'm guessing there was an issue with the tool running externally and not finding one.

2. There was a bug where `project.json` usage for a PCL (instead of net46/dnx/uwp, etc), didn't properly pick up the built-in system references. I've fixed that in v1.4 to work properly.

I'm still not 100% sure of behavior without a project.json or packages.config file.

As to why the nuspec was checked in with it, it simply seems easier than always fighting git as the tool updates the nuspec on every build. If there are no changes, then git doesn't care either. It's entirely possible to remove that dotnet section and have it created on the CI server.

Does that answer your questions?

**Comment by onovotny** [comment]
Hmm...re-checking the source, I stand corrected. It *should* handle having no packages.config present. I'd have to recheck in the debugger what was going on as it should have worked as-is (but didn't).

**Comment by onovotny** [comment]
cross posting my comment from the other thread:

Ugh, this whole thing could have been a giant brain-fart looking at nuget.org. It appears to have been fine originally :(

Very sorry for the false alarm and no hard feelings if you want to revert my commits. If you do revert, the one thing you'll want to keep is the `build.ps1` update to the NuGet download location as that'll pull in v3. the existing url is frozen at v2.

**Comment by michael-wolfenden** [comment]
No problem @onovotny, happens to the best of us. Thanks for clarifying though and thanks in general. Your posts have be invaluable in helping me understand the new nuget monikers and net core.

**Comment by joelhulen** [comment]
Agreed, this has been very helpful to me as well, in better understanding the NuGet dependency intricacies. The question now is whether to roll back these changes and keep the new NuGet url?

**Comment by onovotny** [comment]
In the end, I'd have to ask what benefit do you see from manually calling the cli from the cake script as opposed to having the targets do it on build?

There's no right or wrong answer, I just figure that in the unlikely event the params change, the targets will always be right. I pretty much assumed the cli would be more for building on mono or some other usage that people come up with.

Your call either way.

BTW, there seems to be an extra packages.config in the .pcl folder that has a GitVersion ref in it. That file should prob be removed and if you need the ref there, moved into the project.json (should you keep it).

**Pull request merged**
