### PR TITLE
Refine debug experience via SourceLink

### PR DESCRIPTION
**Pull request by Kesmy**
### The issue or feature being addressed

#464 Refine debug experience via SourceLink

### Details on the issue fix or feature implementation

To support using SourceLink, this
1. Moves all NuSpec properties into the project file
1. Signs the assemblies via project properties
1. Updates the Cake script to use `DotNetCore*` build tools in place of `MSBuild` and `NuGet`
1. Updates `appveyor.yml` to include the `snupkg` artifact

### Confirm the following

- [X]  I started this PR by branching from the head of the latest dev vX.Y branch, or I have rebased on the latest dev vX.Y branch, or I have merged the latest changes from the dev vX.Y branch
- [X]  I have targeted the PR to merge into the latest dev vX.Y branch as the base branch
- [X]  I have included unit tests for the issue/feature (not applicable/no library code changes)
- [X]  I have successfully run a local build

### CODE REVIEW

**Comment by Kesmy** [comment]
@reisenberger Hmm... apparently I can't mark this PR Ready for Review, there's no button for it... can you see if there's one on your view?

**Comment by reisenberger** [comment]
Hi @Kesmy . I have a `Ready for review` button: will try. Not sure also if fact that the base branch (`v704orv710`) has been previously merged may be causing a problem.  I'll retarget this onto `master` shortly.

@Kesmy If you're thinking we're done here, I'll - if ok with you - push a commit onto your PR to add credit to you (😄), update the changelog, bump the gitversionconfig.yaml (I have all this ready already) ... sound ok?  Then probably retarget to `master` and merge :+1: .

**Comment by Kesmy** [comment]
@reisenberger Sounds great to me, thanks.

**Comment by reisenberger** [comment]
@Kesmy  I tried changing the base branch of the PR to `master`, but the branching history is making that want to re-impose the massive project reorganisation of [this commit](https://github.com/App-vNext/Polly/commit/4db50346299f62c2373ceba99d2522a8171c9e27), lists as "can't merge" (too many conflicts to resolve).

Are you happy to take the changes in the 9 files in this PR, and re-impose them afresh on a branch which starts from current `master`? - I just made a `v710` branch for this.  (ie make a new PR targeting `v710`; abandon this PR when happy with new one).  (Alternative could be to merge `master` up into your current branch, but not clear to me based on branch history whether that will come out clean or not)

I can also take this on if you prefer, but you would lose the credit of the commits being "yours" (tho credit of course still in the readme 😀 ).   Just let me know what you prefer.

Thanks again!

**Comment by Kesmy** [comment]
@reisenberger I'll shift these changes over to `v710` this evening (leaving this to  confirm that I saw your message).

**Comment by Kesmy** [comment]
Abandoned for #616 to retarget

**Pull request closed without merging**
