### PR TITLE
update to SDK 7.0.101

### PR DESCRIPTION
**Pull request by SimonCropp**
so we can use c#11

### CODE REVIEW

**Review by martincostello — APPROVED** [review]

**Comment by SimonCropp** [comment]
@martincostello do we still want to keep the appveyor build?

**Comment by martincostello** [comment]
My views are expressed in https://github.com/App-vNext/Polly/issues/980#issue-1500492877 😃

**Comment by joelhulen** [comment]
With Martin planning to move from AppVeyor to GitHub Actions tomorrow, let's hold off on merging this until the new CI/CD process successfully builds.

**Comment by martincostello** [comment]
I still need to work out a NuGet publish flow, but if you rebase onto main you should be good to get a clean xplat CI with coverage now.

**Pull request merged**
