### PR TITLE
Add the new overloads that accept lambda that configures the options

### PR DESCRIPTION
**Pull request by martintmk**
### Details on the issue fix or feature implementation

Just creating this PR to discuss whether adding new extensions that accept lambdas that configure the options is something we want to have built-in. It simplifies the configuration of predicates, events and generators.

Adding retry strategy using the options:
``` csharp
builder.AddRetry(new RetryStrategyOptions
{
    RetryCount = 4,
    BackoffType = RetryBackoffType.Exponential,
    ShouldRetry = new OutcomePredicate<ShouldRetryArguments>().HandleResult(-1).HandleException<InvalidOperationException>(),
    OnRetry = new OutcomeEvent<OnRetryArguments>().Register(()=> Console.WriteLine("Retry occurred!")),
});
```

Using the configure callback:
``` csharp
builder.AddRetry(o =>
{
    o.RetryCount = 4;
    o.BackoffType = RetryBackoffType.Exponential;
    o.ShouldRetry.HandleResult(-1).HandleException<InvalidOperationException>();
    o.OnRetry.Register(() => Console.WriteLine("Retry occurred!"));
});
```

Note that the overload that accepts the options directly needs to stay as it will be API that can integrate with `IOptions`.

**Is the second API (in addition to the first one) something we want to have built-in?**

### Confirm the following

- [ ]  I started this PR by branching from the head of the default branch
- [ ]  I have targeted the PR to merge into the default branch
- [ ]  I have included unit tests for the issue/feature
- [ ]  I have successfully run a local build

### CODE REVIEW

**Comment by martincostello** [comment]
Seems a reasonable approach to me. I would imagine that it should compose well with DI so that people could load configuration settings from configuration?

For example:

```csharp
builder.AddRetry(o =>
{
    o.RetryCount = configuration.Get<int>("MyRetryCount");
});
```

**Comment by juraj-blazek** [comment]
It's one more overload for each strategy, but I think it makes the configuration of the predicates/events/generators much more readable

**Comment by martintmk** [comment]
> Seems a reasonable approach to me. I would imagine that it should compose well with DI so that people could load configuration settings from configuration?
> 
> For example:
> 
> ```cs
> builder.AddRetry(o =>
> {
>     o.RetryCount = configuration.Get<int>("MyRetryCount");
> });
> ```

For DI scenario I would recommend this approach (still does not negate the approach above):

``` csharp
return new ServiceCollection()
    .Configure<RetryStrategyOptions>(options =>
    {
      o.RetryCount = 4;
      o.BackoffType = RetryBackoffType.Exponential;
      o.ShouldRetry.HandleResult(-1).HandleException<InvalidOperationException>();
      o.OnRetry.Register(() => Console.WriteLine("Retry occurred!"));
    })
    .AddResilienceStrategy("my-timeout", context =>
    {
        // resolve options from DI
        var options = context.ServiceProvider.GetRequiredService<IOptions<RetryStrategyOptions>>().Value;
        context.Builder.AddRetry(options);
    })
```

You can just resolve complete configured options from DI.

**Comment by martintmk** [comment]
> OK in my use case then I'd probably not use the new overload and do it like your example, as I would want some values to be in external configuration (e.g. JSON files etc.) not hard-coded.
> 
> ```cs
> return new ServiceCollection()
>     .Configure<RetryStrategyOptions, IConfiguration>((o, configuration) =>
>     {
>       o.RetryCount = configuration.Get<int>("MyRetryCount");
>       o.BackoffType = RetryBackoffType.Exponential;
>       o.ShouldRetry.HandleResult(-1).HandleException<InvalidOperationException>();
>       o.OnRetry.Register(() => Console.WriteLine("Retry occurred!"));
>     })
>     .AddResilienceStrategy("my-retry", context =>
>     {
>         // resolve options from DI
>         var options = context.ServiceProvider.GetRequiredService<IOptions<RetryStrategyOptions>>().Value;
>         context.Builder.AddRetry(options);
>     })
> ```

You can also use this right?

``` csharp 
return new ServiceCollection()
    .Configure<RetryStrategyOptions>(configuration) // this binds values from configuration
    .Configure<RetryStrategyOptions>(o =>
    {
      // just configure the callbacks here
      o.ShouldRetry.HandleResult(-1).HandleException<InvalidOperationException>();
      o.OnRetry.Register(() => Console.WriteLine("Retry occurred!"));
    })
    .AddResilienceStrategy("my-retry", context =>
    {
        // resolve options from DI
        var options = context.ServiceProvider.GetRequiredService<IOptions<RetryStrategyOptions>>().Value;
        context.Builder.AddRetry(options);
    })
```

**Comment by martintmk** [comment]
Won't be required after #1200.

**Pull request closed without merging**
