### PR TITLE
Added `readonly` modifier to private fields which are never changed

### PR DESCRIPTION
**Pull request by Lehonti**
### Confirm the following

- [x]  I started this PR by branching from the head of the default branch
- [x]  I have targeted the PR to merge into the default branch
- [ ]  I have included unit tests for the issue/feature (N/A)
- [x]  I have successfully run a local build

### CODE REVIEW

**Comment by martincostello** [comment]
Thanks for your contribution.

As you can see, the build is now failing due to readonly being incompatible with other uses of these fields in the code. It may be that all of these fields are already not readonly for that very reason.

Please run the build locally and fix any issues to continue with this contribution.

**Comment by Lehonti** [comment]
I managed to reproduce the errors in my local environment, and removed the problematic `readonly` modifiers

**Comment by martincostello** [comment]
The changes are now hitting lint errors. Please get a full clean build locally before pushing further changes.

**Comment by Lehonti** [comment]
No problem. I planned to fix the linting issues in a future PR, but I didn't have any idea that they were configured to make a build fail. It's understandable, of course. You want to keep the code clean.

The built succeeded in my machine without errors or warnings.

**Review by martincostello — APPROVED** [review]

**Comment by martincostello** [comment]
Thanks!

**Pull request merged**
