### PR TITLE
Dont lock on hot path reads if we can help it

### PR DESCRIPTION
**Pull request by christopherbahr**
I may be missing something here but I think we can get away without the locking in `OnActionPreExecute` since enum reads are atomic. I don't think this actually protects us from anything.

I also added a check in the reader so if we aren't going to do any writing we can do the read without locking. 

The only edge case this introduces is if we make our read, the circuit is not open, someone sets it to open, and we return open without ever checking whether we should go to half open (which we almost certainly should not do that soon after opening anyway but it's net necessarily prevented). 

Before these changes were made the reader would have gotten a lock first though and the write wouldn't have executed until we were done anyway so there's not actually behavior difference there.

### CODE REVIEW

**Comment by reisenberger** [comment]
@christopherbahr Thanks!  On a quick read this looks good - I'd like to have a little more time to think over the edge case/s, so give me couple days on that ... (agree there is the edge case you mentioned; and it probably pans out as you say)... Optimisations always welcome, though, so thanks!

I also have some CircuitBreaker timing tets (testing 100000 calls through the breaker) which we put together when performance-testing implementation options for the new `AdvancedCircuitBreaker`: it produces stats for well-behaving underlying systems, frequently faulting systems, etc ... so I'll run the change through the performance-tester too and see what we get!

Your optimisation also depends on the switch expression only being evaluated once ... I'd eat my hat if that wasn't the way it was implemented :smile: (and think remember reading that somewhere), but shout if you know different! 

Thanks!

**Comment by christopherbahr** [comment]
The spec says the first step in evaluating a `switch` statement is 
"The switch expression is evaluated and converted to the governing type."
http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-334.pdf page 232

That reads to me like it will store the outcome of the switch expression rather than recalculating it. (I've seen someone verify this by looking at the IL but the compiler is allowed to do whatever it wants as long as it follows the spec so I'm not sure we want to rely on that). 

That said if you're worried about it I can just copy the value into a local variable and then switch based on that. 

Let me know how the performance testing goes. It was actually during performance/load testing something that depends on Polly that I came across this.

**Comment by reisenberger** [comment]
@christopherbahr Many thanks for this PR!  Squeezed in some time for performance-testing after the recent major feature work, and agree that this is a valuable optimisation to the hot path.  [This commit](https://github.com/App-vNext/Polly/pull/130/commits/3b32ec5e6fbeb77b76c6e36b584c5127a9f48509) contains an equivalent change to the new `CircuitStateController`, and we expect this to be released as part of #130 in the next few days.  I am not proposing we do any special workaround for the `switch` statement; I agree with your assessment of the edge case in your original post.
 
The next phase of Polly (have you seen the [Roadmap](https://github.com/App-vNext/Polly/wiki/Polly-Roadmap)?) is very much intended to support high volume / low latency scenarios, with new policies such as cache, fallback, and parallelism-throttle for bulkhead isolation or (if user requires) load-shedding.  If you are working in a high-throughput/low latency environment, now is a great time to provide any feedback you have or feature requests under the related [feedback issue](https://github.com/App-vNext/Polly/issues/90).  
 
Also continuing to develop the performance test bed for Polly: if you are able to share the kind of throughputs you are dealing with, whether sync or async, etc (post here or email me at software[at]reisenberger.net if you prefer), it might be interesting to put your kind of numbers through the test bed?
 
Thanks

**Comment by joelhulen** [comment]
These changes were incorporated into PR #130 

Thanks for your great contribution!

**Pull request closed without merging**
