### PR TITLE
Rate limiter

### PR DESCRIPTION
**Pull request by YarekTyshchenko**
### The issue or feature being addressed

This PR is a resurrection of #666 only because the author seems to be unreachable. Most of the work has already been done by @reisenberger 

Solves Issue #260

### Confirm the following

- [ ]  I started this PR by branching from the head of the latest dev vX.Y branch, or I have rebased on the latest dev vX.Y branch, or I have merged the latest changes from the dev vX.Y branch
- [ ]  I have targeted the PR to merge into the latest dev vX.Y branch as the base branch
- [ ]  I have included unit tests for the issue/feature
- [ ]  I have successfully run a local build

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/App-vNext/Polly?pullRequest=894) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/App-vNext/Polly?pullRequest=894) before we can accept your contribution.<br/><br/>:x: YarekTyshchenko [sign now](https://cla.dotnetfoundation.org/App-vNext/Polly?pullRequest=894)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/App-vNext/Polly?pullRequest=894) it.</sub>

**Comment by derigel23** [comment]
Any progress on accepting & merging this PR?

**Comment by martincostello** [comment]
I'm planning on reviving the other original PR imminently, but with some additional changes on top based on some minor tweaks we made in a private form we've been running in production for the last 18 months.

**Comment by martincostello** [comment]
Thank you for trying to resurrect #666 via this PR @YarekTyshchenko.

As this has been in draft for a while now I'm going to close this.

I've created a new PR with the aim to get the rate limiting policy merged here - #903.

Please address any comments on the functionality there.

**Pull request closed without merging**
