### PR TITLE
Added Noop policy method

### PR DESCRIPTION
**Pull request by NielsKlosterAndreassen**
In a large application it is sometimes nice to be able to pass exception policies around. When doing so, it is necessary to have a policy equivalent to not wrapping the call in a policy. 

This is my first public pull request ever, so comments and critique is welcome.

### CODE REVIEW

**Comment by bchavez** [comment]
:+1: for this

**Comment by bchavez** [comment]
This seems to work just as well:

```
    public static class Safely
    {
        public static PolicyBuilder HandleAny()
        {
            return Policy.Handle<Exception>();
        }
    }
```
:+1:

**Comment by reisenberger** [comment]
@NielsKlosterAndreassen @mattgwagner  The AppvNext team have now taken on the stewardship of Polly.  Although this PR is old, just updating you that this (being able to specify no-retry as a `Policy`) seems a reasonable idea, that several people have asked for.  The retry-count-of-zero approach is preferred for this and we should be able to merge this in due course.  See #37 if you want to follow / help implement this!

**Comment by reisenberger** [comment]
Closing this PR in favour of #37

**Pull request closed without merging**
