### PR TITLE
Retry forever with wait

### PR DESCRIPTION
**Pull request by nedstoyanov**
Added retry forever with await.

### CODE REVIEW

**Comment by reisenberger** [comment]
@nedstoyanov Very many thanks for your continuing involvement in Polly, and for your PR!  I am assuming this is an implementation for #24 

I would like to recommend to @joelhulen that we incorporate this, if we can fix up a few issues first:

[1] Can you consider adding async support, so that `.WaitAndRetryForever()` could launch for both sync and async?  There is a partial class pattern that should be easy to follow between `RetrySyntax` / `RetrySyntaxAsync`, `RetryPolicyStateWithSleep / Async` (see that for how to handle async sleep), `WaitAndRetryAsyncSpecs` (see for async test examples). The async tests tend to closely mimic sync tests, but with `.RaiseExceptionAsync()`, and `policy.Awaiting(` in place of `policy.Invoking(` . Let me know if you want any further guidance on this!
 
[2] Can you consider `int.MaxValue` defence?  Maybe something as simple as `if (_errorCount < int.MaxValue) _errorCount += 1;`.  While it is unlikely a failing retryforever might reach int.MaxValue, as a library, we should probably defend.

[3] Polly v4.0.0 published last night with new circuit breaker support; so (with apologies) you would need to rebase on latest.

Thanks again @nedstoyanov !  This is looking like a good implementation for #24

**Comment by nedstoyanov** [comment]
Thanks for your comments @reisenberger, I rebased my branch and I am fixing up the issues.
This is my first PR so not sure what is the process here. Do I close this PR and open a new one, or is there a way to fix this one?

**Comment by nedstoyanov** [comment]
@reisenberger regarding the error count, should we just stop incrementing once it reaches `int.MaxValue`? Alternatively we can return `false` from `CanRetry` but that won't really be retrying forever.

**Comment by reisenberger** [comment]
@nedstoyanov re: 

>should we just stop incrementing once it reaches  int.MaxValue ? 
>Alternatively we can return  false  from  CanRetry  but that won't really be retrying forever. 

Let's just stop incrementing once it reaches int.MaxValue.  It's better that retry forever, really means retry forever.

**Comment by joelhulen** [comment]
@nedstoyanov Since you've already rebased your branch, as long as you commit any merges or additional changes, they'll automatically be added to this PR. Just add a comment here once you're finished with your changes so we can review, and, ultimately, accept your PR.

**Comment by nedstoyanov** [comment]
@reisenberger @joelhulen I think this PR should be ready. Are you able to review?

**Comment by reisenberger** [comment]
@nedstoyanov Many thanks! I will aim to review in the next few days.

**Comment by reisenberger** [comment]
Many thanks @nedstoyanov for your contribution!  I have been able so far to review the operating code (not the tests), and had only three small comments: 

+ `_errorCount += 1` needs defending against int.maxValue, within `CanRetryAsync(...)` of `RetryPolicyStateWithSleepDurationProvider`, in the same way as in `CanRetry(...)` 
+ Please can the final overload in each of `RetrySyntax` and `RetrySyntaxAsync`, return a `RetryPolicy` rather than a `ContextualPolicy`
* [minor] Please could all the new overloads in `RetrySyntax` and `RetrySyntaxAsync` indicate, in their `<exception cref="System.ArgumentNullException">` section, that an `ArgumentNullException` may also be thrown for `sleepDurationProvider` (sample style for multiple ArgumentNullExceptions in the similar WaitAndRetry overloads)

@joelhulen @nedstoyanov After I have read the xUnit tests will comment further.

Many thanks!

**Comment by nedstoyanov** [comment]
Thanks, @reisenberger I'll try and fix these issues in the meantime.

**Comment by reisenberger** [comment]
Very many thanks again @nedstoyanov for your contribution and PR!  Here a few things to do on test coverage, to make this good to go!
 
_Below comments apply equally for `WaitAndRetryForeverSpecs` and `WaitAndRetryForeverAsyncSpecs` (action in both)_
 
* `Should_create_new_state_for_each_call_to_policy()` is not relevant for retry-forever policies - can be deleted. 

* `Should_throw_when_onretry_action_is_null_without_context_when_using_provider_overload` and `Should_throw_when_onretry_action_is_null_with_context_when_using_provider_overload` can be deleted; they duplicate the third and fourth tests. (In the WaitAndRetrySpecs model you may have followed, they were not duplicates because of the different possible ways of specifying waits.)
 
* Can we add the test `Should_call_onretry_on_each_retry_with_the_current_exception()`?  Model to follow in `WaitAndRetry/AsyncSpecs`.

* The test `Should_not_call_onretry_when_no_retries_are_performed()` does not amend in any way the `retryCounts = new List<int>()` collection, so the assertion `retryCounts.Should().BeEmpty();` does not test anything.  Need to use the `onRetry` delegate to add something to the `retryCounts` collection on each retry, so that the final `Should().BeEmpty();` has meaning.  See good example in `RetrySpecs`.  (_This issue also exists in the versions in WaitAndRetry/AsyncSpecs, which you may have followed; feel free to fix it there also if you want_.)  
 
 
_On the async tests:_
 
* Place `WaitAndRetryForeverAsyncSpecs` in same namespace as other tests, `Polly.Specs`
* We ought to add the tests on `CancellationToken` support.  These can follow exactly the form in `RetryForeverAsyncSpecs`: we need all tests from `Should_execute_action_when_non_faulting_and_cancellationtoken_not_cancelled()` to the end of the file.  Just substitute `.WaitAndRetryForeverAsync(provider)` for `.RetryForeverAsync()`, and these should be good to go!  
 
 
@nedstoyanov, Very many thanks again for your contribution!  One of the strengths of the Polly codebase is the thoroughness of the test coverage; but we appreciate this does mean adding a lot of tests when adding a new policy (as you have done). So - thank you for your persistence with this!   Let me know if you want any assistance with the above – or if you have questions.
 
Many thanks!

**Comment by nedstoyanov** [comment]
Thanks for the feedback @reisenberger, I'll make the changes in the next few days. Apologies for the holes in the code I am still relatively new to Polly.

**Comment by mgj** [comment]
Im sorry i dont have much to add, i just wanted to voice my appreciation for the work being done here - This PR will be very very useful to me. If there is anything I can help you with regarding this PR, please let me know. Thanks

**Comment by reisenberger** [comment]
@mgj Good to hear ;-)
@nedstoyanov No problem.

**Comment by nedstoyanov** [comment]
@reisenberger I have implemented your suggestions and also fixed up the `Should_not_call_onretry_when_no_retries_are_performed()` test in the WaitAndRetry/AsyncSpecs

**Comment by reisenberger** [comment]
@nedstoyanov, Many thanks for your contribution! - and also for fixing up the WaitAndRetry/AsyncSpecs.  All looks good to go!  AppvNext hoping to push this out to Nuget as v4.1.0 in the next 24-48 hours.  :+1:

**Comment by joelhulen** [comment]
Thanks for the great work, @nedstoyanov, and for the thorough review and helpful comments as always, @reisenberger!

Merged :+1:

**Pull request merged**
